[cpu]
core=normal
cputype=auto
cycles=8000

[dosbox]
memsize=16

[render]
scaler=normal2x

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount C C:\Users\57313\QuinteroCarrillo-post1-u5
C:
echo DOSBox listo. Directorio de trabajo: C:\
cls


